name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install yubico-piv-tool
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential check libpcsclite-dev
        curl -sLO https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-1.7.0.tar.gz
        tar -zxvf yubico-piv-tool-1.7.0.tar.gz
        cd yubico-piv-tool-1.7.0
        ./configure --prefix=/usr
        make
        sudo make install

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

